// partA.js: p2 partA: recreation of Nightingale plot
// Copyright (C)  2022 University of Chicago. All rights reserved.
/*
This is only for students and instructors in the 2022 CMSC 23900 ("DataVis") class, for use in that
class. It is not licensed for open-source or any other kind of re-distribution. Do not allow this
file to be copied or downloaded by anyone outside the 2022 DataVis class.
*/
'use strict';
import {
  captionText, capsMonth,
  // what do you want to import from common.js?
  // v.v.v.v.v.v.v.v.v.v.v.v.v.v.v  begin student code
  fnColor, dataProc, outColor,
  // ^'^'^'^'^'^'^'^'^'^'^'^'^'^'^  end student code (1L in ref)
  d3,
} from './common.js';

// new things you might want to use for partA()
// v.v.v.v.v.v.v.v.v.v.v.v.v.v.v  begin student code
// ^'^'^'^'^'^'^'^'^'^'^'^'^'^'^  end student code (14L in ref)

// how you make part A
export const partA = (id, csvData) => {
  const svg = d3.select(`#${id}`);
  // v.v.v.v.v.v.v.v.v.v.v.v.v.v.v  begin student code
  const data = dataProc(csvData);

  // creates padding
  svg.append("rect")
    .attr("x", 0)
    .attr("y", 0)
    .attr("width", 1100)
    .attr("height", 601)
    .attr("fill", fnColor.bkgd)

  /* adds labeling text
  I know this is copy pasta but I'll fix it when I have the chance.
  I'm also not very familiar with js so it's hard for me to format
  these into loops. */
  svg.append("text")
    .attr("x", 851.8)
    .attr("y", 34)
    .attr("text-anchor", "middle")
    .attr("font-size", "14px")
    .text("1.")
  svg.append("text")
    .attr("x", 229.7)
    .attr("y", 34)
    .attr("text-anchor", "middle")
    .attr("font-size", "14px")
    .text("2.")
  svg.append("text")
    .attr("x", 851.8)
    .attr("y", 48)
    .attr("text-anchor", "middle")
    .attr("font-size", "14px")
    .text("APRIL 1854 to MARCH 1855")
  svg.append("text")
    .attr("x", 229.7)
    .attr("y", 48)
    .attr("text-anchor", "middle")
    .attr("font-size", "14px")
    .text("APRIL 1855 to MARCH 1856")
  svg.append("text")
    .attr("x", 550)
    .attr("y", 27)
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .text("DIAGRAM of the CAUSES of MORTALITY")
  svg.append("text")
    .attr("x", 550)
    .attr("y", 46)
    .attr("text-anchor", "middle")
    .attr("font-size", "18px")
    .text("in the ARMY in the EAST")
  svg.append("text")
    .attr("x", 85)
    .attr("y", 390.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[0][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 408.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[0][1])
  svg.append("text")
    .attr("x", 85)
    .attr("y", 425.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[1][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 443.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[1][1])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 460.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[1][2])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 478.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[1][3])
  svg.append("text")
    .attr("x", 85)
    .attr("y", 495.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[2][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 513.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[2][1])
  svg.append("text")
    .attr("x", 85)
    .attr("y", 530.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[3][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 548.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[3][1])
  svg.append("text")
    .attr("x", 85)
    .attr("y", 565.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[4][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 583.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[4][1])

  // sliced the data into halves
  const mid = Math.ceil(data.length / 2);
  const firstHalf = data.splice(0, mid);
  const secondHalf = data.splice(-mid);

  /* makes arcs: starts at 3pi/2 and increments by 1/6pi
  found outer radius by knowing that 
  area of sector = pi*r^2/12, where area of sector is death rate */
  const arcgen0 = (d, i, r) =>
    d3.arc()
      .innerRadius(0)
      .outerRadius(Math.sqrt(r * 12 / Math.PI)*5.1)
      .startAngle(3*Math.PI / 2 + 1/6*Math.PI*i)
      .endAngle(3*Math.PI / 2 + 1/6*Math.PI*i + 1/6*Math.PI)();

  /* I see that this is copy pasta code so I'll recode this when
  or if I have time */
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.zWej')
    .attr('d', (d, i) => arcgen0(d, i, d.zRate))
    .attr('fill', fnColor.blue)
    .attr('stroke-width', 0)
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.oWej')
    .attr('d', (d, i) => arcgen0(d, i, d.oRate))
    .attr('fill', fnColor.gray)
    .attr('stroke-width', 0)
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.wWej')
    .attr('d', (d, i) => arcgen0(d, i, d.wRate))
    .attr('fill', fnColor.pink)
    .attr('stroke-width', 0)
 
  // this makes the outlines for the wedges
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.zWej-outlines')
    .attr('d', (d, i) => arcgen0(d, i, d.zRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.blue)
    .attr('stroke-width', 1.2)
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.oWej-outlines')
    .attr('d', (d, i) => arcgen0(d, i, d.oRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.gray)
    .attr('stroke-width', 1.2)
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.wWej')
    .attr('d', (d, i) => arcgen0(d, i, d.wRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.pink)
    .attr('stroke-width', 1.2)

  // here begins the next graph (the one on the left)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.zWej')
    .attr('d', (d, i) => arcgen0(d, i, d.zRate))
    .attr('fill', fnColor.blue)
    .attr('stroke-width', 0)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.wWej')
    .attr('d', (d, i) => arcgen0(d, i, d.wRate))
    .attr('fill', fnColor.pink)
    .attr('stroke-width', 0)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.oWej')
    .attr('d', (d, i) => arcgen0(d, i, d.oRate))
    .attr('fill', fnColor.gray)
    .attr('stroke-width', 0)
 
  // makes outlines for wedges
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.zWej-outlines')
    .attr('d', (d, i) => arcgen0(d, i, d.zRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.blue)
    .attr('stroke-width', 1.2)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.wWej')
    .attr('d', (d, i) => arcgen0(d, i, d.wRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.pink)
    .attr('stroke-width', 1.2)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.oWej-outlines')
    .attr('d', (d, i) => arcgen0(d, i, d.oRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.gray)
    .attr('stroke-width', 1.2)

  // here makes the month tags
  svg.append('text')
    .text(d => capsMonth)
    .attr('class', '.month')
    .attr('transform', 'translate(-106,-28)')
    .attr('font-size', "9.5px")
    .attr('text-anchor', 'middle')
  // ^'^'^'^'^'^'^'^'^'^'^'^'^'^'^  end student code (132L in ref)
};
